available_primitives: torch.add,torch.sub,torch.mul,torch_protected_div,torch_mean,torch_median,torch.abs,torch_protected_sqrt
batch_size: 128
server_learning_rate: 0.0005
client_learning_rates:
- 0.005
- 0.02
- 0.1
crossover_rate: 0.6
crossover_type: cxOnePoint
dataset_name: pathmnist
death_prob: 0.0
evaluation_split_mode: train_val_test
custom_model_mode: default
custom_model_code: ''
elitism_size: 1
generations: 20
server_warmup_epochs: 2
gp_fitness_metric: accuracy
gp_initialization: genHalfAndHalf
gp_patience: 4
gp_transfer_learning: full_reuse
iid: false
imbalance_rate: 0.5
initial_eligible_clients: 2
individuals: 50
learning_rate: 0.0005
local_model_epochs: 15
round_train_schedule_mode: auto
round_train_schedule_percentages: []
round_client_allocation_mode: auto
round_client_allocation_percentages: []
max_tree_size: 5
method: fed_avg
min_tree_size: false
mutation_subtree_maxsize: 2
momentum: 0.9
mu: 1
fedprox_weighted: true
new_client_prob: 0.0
mutation_rate: 0.4
mutation_type: mutUniform
num_clients: 2
repeat: 1
seed: 0
selection_type: selTournament
server_data_percentage: 0.1
train_val_split: 0.9
weights_sending_frequency: 3
